src/objects/Org_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Period_Term__c</fullName>
        <label>Period Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Configuration</label>
</CustomObject>

src/objects/Product_Table__c.object
<CustomObject>
    <fields>
        <fullName>Added_Date__c</fullName>
        <label>Added Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Warehouses__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipName>MyProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Warehouse__c.object
<CustomObject>
    <fields>
        <fullName>Period_End__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Start__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductTriggerHandler.cls
public class ProductTriggerHandler {
    public static Org_Configuration__c period_Term { 
        get { 
            return Org_Configuration__c.getInstance(); 
        } 
        private set; 
    }
    
    public static void insertMethod (List<Product_Table__c> products) {
        List<Warehouse__c> defaultWarehouses = listWarehouses();
        List<Warehouse__c> newWarehouses = new List<Warehouse__c>() ;
        for(Product_Table__c p : products) { 
            if (p.Added_Date__c == NULL) {
                p.Added_Date__c = Date.today();
            }
	        if (!checkDatePeriod(defaultWarehouses,p.Added_Date__c)){
				defaultWarehouses.add(new Warehouse__c(Period_Start__c = p.Added_Date__c,
                Period_End__c   = p.Added_Date__c.addDays(period_Term.Period_Term__c.intValue())));
                newWarehouses.add(new Warehouse__c(Period_Start__c = p.Added_Date__c,
                Period_End__c   = p.Added_Date__c.addDays(period_Term.Period_Term__c.intValue()) , 
                Name = 'Warehouse '  + String.valueOf( p.Added_Date__c) + '  ' +  String.valueOf(p.Added_Date__c.addDays(period_Term.Period_Term__c.intValue()))));
            }
       }
        
        insert newWarehouses;
       	List<Warehouse__c> defaultWarehouseNew = listWarehouses();
         for(Product_Table__c p : products) { 
           for (Warehouse__c dw : defaultWarehouseNew){
                if (dw.Period_Start__c <= p.Added_Date__c && dw.Period_End__c >=  p.Added_Date__c ){
                	 p.Warehouses__c = dw.id;
                } 
            }
       	}
    }
       
    private static Boolean checkDatePeriod(List<Warehouse__c> defaultWarehouses , Date dt){
		for (Warehouse__c dw : defaultWarehouses){
        	if (dw.Period_Start__c <= dt && dw.Period_End__c >= dt ){
            	return true;
            } 
		}
        return false;
	}
    private static List<Warehouse__c> listWarehouses (){
      
       List<Warehouse__c> defaultWarehouse = [
        	SELECT Id, Period_Start__c, Period_End__c
            FROM Warehouse__c 
      	]; 
        return defaultWarehouse;
        
    }
}