src/objects/Org_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Period_Term__c</fullName>
        <label>Period Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Configuration</label>
</CustomObject>

src/objects/Product_Table__c.object
<CustomObject>
    <fields>
        <fullName>Product_D__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_price__c</fullName>
        <label>Unit price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApexTestControllers.cls
@isTest
public class ApexTestControllers {
    @testSetup
    public static void setup() {
       
		insert new Org_Configuration__c(period_Term__c = 5);

    	List<Product_Table__c> productTable = new List<Product_Table__c>();
        for(Integer i=0;i<10;i++) {
     		productTable.add(new Product_Table__c(Name = 'product name ' + i,Unit__c = i,Unit_price__c= i + 5,Product_D__c = 'test product' + i));
        }
        insert productTable;        
  		
        List<Contact> contact = new List<Contact>();
        for(Integer i=0;i<5;i++) {
            contact.add(new Contact(FirstName = 'firstName' + i,LastName = 'lastName' + i,Email = 'email' + i + '@email.ru'));
        }
        insert contact;        
 
    }
    
	@isTest
    public static void testProductListController(){
        PageReference pageRef = Page.Product_List;
        pageRef.getParameters().put('message','message');
        test.setCurrentPageReference(pageRef);
        ProductListController ListController = new ProductListController();
        List<Product_Table__c> products = ProductListController.getProducts();
    }

    @isTest
    public static void testProductViewController(){
        Product_Table__c  product_Table = [SELECT Id FROM Product_Table__c LIMIT 1];
        PageReference pageRef = Page.Product_List;
        pageRef.getParameters().put('id',product_Table.id);
        test.setCurrentPageReference(pageRef);
        ProductViewController ViewController = new ProductViewController();
    }
    
    @isTest
    public static void testProductBuyController(){
        Contact  contact = [SELECT id,firstName, lastName, email FROM Contact LIMIT 1];
	    testAddBuy(4,contact.email,contact.firstName,contact.lastName, 1);
        testAddBuy(4,contact.email,'firstName99','lastName99', 1);
        testAddBuy(2,'','','', 1); 
        testAddBuy(2,contact.email,'','', 1);
		testAddBuy(2,'email11-email.ru','','', 1);
        testAddBuy(2,contact.email,contact.firstName,'', 1);
        testAddBuy(0,contact.email,contact.firstName,contact.lastName, 0);
        testAddBuy(0,contact.email,contact.firstName,contact.lastName, 3);
        testAddBuy(4,'email11@email.ru',contact.firstName,contact.lastName, 1);
    }
    
	private static void testAddBuy(Integer unit, String email, String firstName, String lastName, Decimal amountProd ) {
    	Product_Table__c product_Table = [SELECT Id FROM Product_Table__c WHERE Unit__c >=: unit LIMIT 1];
        PageReference pageRef = Page.Product_List;
        pageRef.getParameters().put('id',product_Table.id);
        test.setCurrentPageReference(pageRef);
        ProductBuyController buyController = new ProductBuyController();
        buyController.email = email;
        buyController.getNameContact();
        buyController.firstName = firstName;
        buyController.lastName = lastName;
        buyController.amountProd = amountProd;
        buyController.saveInfoBuy();
    }    
}