src/objects/Product_Table__c.object
<CustomObject>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Product_D__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_price__c</fullName>
        <label>Unit price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Warehouses__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipName>MyProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Warehouse__c.object
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductListController.cls
public class ProductListController {
   
    private String message{get;set;}
  
    public ProductListController (){
    	chkMsg();      
    }
    public static List<Product_Table__c> getProducts() {
        return [
            SELECT
                Id,
                Unit_Price__c,
                Image_url__c,
                Product_D__c,
                Warehouses__r.Name,
                Unit__c,
                Name
            FROM Product_Table__c
        ];
    }
    
    private void chkMsg(){
        this.message = ApexPages.CurrentPage().GetParameters().Get('message');
        if( this.message != null){
               ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, this.message)); 
        }  
    }
    
}