src/objects/Product_Table__c.object
<CustomObject>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Product_D__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductViewController.cls
public class ProductViewController {

    public String NameProd{get;set;}
    public Decimal AmountProd{get;set;}
    public String DescriptionProd{get;set;}
    public String ImageProd{get;set;}
    public String ProdId{get;set;}    

    public ProductViewController (){
        viewPage();  
    }
    
    private void viewPage(){
		this.ProdId= Apexpages.currentPage().getparameters().get('id');
        IF (this.ProdId != null){
        	Product_Table__c Prod = [SELECT Name, Image_URL__c, Product_D__c, Unit__c FROM Product_Table__c WHERE id=:this.ProdId ];
         	this.NameProd        = Prod.Name;
         	this.ImageProd       = Prod.Image_URL__c;
         	this.AmountProd      = Prod.Unit__c == null ?  0 :  Prod.Unit__c;
         	this.DescriptionProd = Prod.Product_D__c;
        }
    }
  
}